run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gofumpt

linters-settings:
  revive:
    severity: warning
  gofumpt:
    extra-rules: true
